CREATE TABLE LICENSE(
    LIC_CODE CHAR(4),
    LIC_NAME VARCHAR2(50 CHAR) NOT NULL,
    CONSTRAINT PK_LICENSE PRIMARY KEY(LIC_CODE)
);

INSERT INTO LICENSE(LIC_CODE, LIC_NAME) VALUES('L001', '정보처리산업기사');
INSERT INTO LICENSE(LIC_CODE, LIC_NAME) VALUES('L002', '정보처리기사');
INSERT INTO LICENSE(LIC_CODE, LIC_NAME) VALUES('L003', '정보보안산업기사');
INSERT INTO LICENSE(LIC_CODE, LIC_NAME) VALUES('L004', '정보보안기사');
INSERT INTO LICENSE(LIC_CODE, LIC_NAME) VALUES('L005', 'SQLD');
INSERT INTO LICENSE(LIC_CODE, LIC_NAME) VALUES('L006', 'SQLP');

CREATE TABLE GRADE(
    GR_CODE CHAR(4),
    GR_NAME VARCHAR2(10 CHAR) NOT NULL,
    CONSTRAINT PK_GRADE PRIMARY KEY(GR_CODE)
);

INSERT INTO GRADE(GR_CODE, GR_NAME)VALUES('G001', '고졸');
INSERT INTO GRADE(GR_CODE, GR_NAME)VALUES('G002', '초대졸');
INSERT INTO GRADE(GR_CODE, GR_NAME)VALUES('G003', '대졸');
INSERT INTO GRADE(GR_CODE, GR_NAME)VALUES('G004', '석사');
INSERT INTO GRADE(GR_CODE, GR_NAME)VALUES('G005', '박사');

CREATE TABLE ALBA(
    AL_ID CHAR(8), -- 알바생코드, ex) A0000001
    AL_NAME VARCHAR2(20) NOT NULL, -- 이름
    AL_AGE NUMBER(3) NOT NULL, -- 나이
    AL_ZIP VARCHAR2(7) NOT NULL, -- 우편번호
    AL_ADD1 VARCHAR2(200) NOT NULL, -- 주소
    AL_ADD2 VARCHAR2(200) NOT NULL, -- 주소
    AL_HP VARCHAR2(15)  NOT NULL, -- 휴대폰    
    GR_CODE CHAR(4) NOT NULL, -- 학력
    AL_GEN CHAR(1) NOT NULL, -- F:여자,  M:남자
    AL_MAIL VARCHAR2(100) NOT NULL, -- 이메일
    AL_CAREER VARCHAR2(200), --  경력사항
    AL_SPEC VARCHAR2(500), -- 특기사항
    AL_DESC VARCHAR2(500), -- 비고
    AL_IMG VARCHAR2(300), -- 프로필사진 경로
    CONSTRAINT PK_ALBA PRIMARY KEY (AL_ID),
    CONSTRAINT FK_ALBA_GRADE FOREIGN KEY (GR_CODE) REFERENCES GRADE(GR_CODE)
);

CREATE TABLE LIC_ALBA(
    AL_ID CHAR(8), -- 알바생 코드
    LIC_CODE CHAR(4), -- 자격증 코드
    LIC_DATE VARCHAR2(30), -- 취득일
    LIC_IMG BLOB, -- 자격증 사본
    CONSTRAINT PK_LIC_ALBA PRIMARY KEY(AL_ID, LIC_CODE),
    CONSTRAINT FK_LIC_ALBA_ALBA FOREIGN KEY(AL_ID) 
        REFERENCES ALBA(AL_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LIC_ALBA_LICENSE FOREIGN KEY(LIC_CODE) 
        REFERENCES LICENSE(LIC_CODE) ON DELETE SET NULL
);

INSERT INTO ALBA (
    AL_ID,    AL_NAME,    AL_AGE, AL_ZIP, AL_ADD1, 
    AL_ADD2,    AL_HP,    AL_SPEC,   AL_DESC,   
    GR_CODE,    AL_CAREER,   AL_GEN,    AL_MAIL
)
SELECT 'A'||LPAD(ROWNUM, 7, '0') , MEM_NAME, 
    23,
    NVL(MEM_ZIP, '123-457'), NVL(MEM_ADD1, '대전 오류'), NVL(MEM_ADD2, '대덕인재개발원'), 
    NVL(MEM_HP, '000-000-0000'), '스펙', '자기소개', 'G003', MEM_JOB, 
    DECODE(SUBSTR(MEM_REGNO2, 1, 1), '1', 'M', 'F'),
    NVL(MEM_MAIL, 'AA@NAVER.COM')
FROM MEMBER;

INSERT INTO LIC_ALBA (AL_ID, LIC_CODE, LIC_DATE)
SELECT AL_ID, 'L001', SYSDATE
FROM ALBA;
           
INSERT INTO LIC_ALBA(AL_ID, LIC_CODE)
SELECT AL_ID, 'L004'
FROM (SELECT ROWNUM RNUM, AL_ID FROM ALBA)
WHERE MOD(RNUM,2) = 0;

COMMIT;